---
title: "AlphaFold"
output:
  html_document:
    toc: false
    toc_float: false
---


This is a training course aimed at users wishing to use High Performance Computing and Cloud environments to learn [AlphaFold](https://www.nature.com/articles/s41586-021-03819-2). AlphaFold performs predictions of protein structure.


## Trainers

Have a list of the people delivering the course if it is needed. 
However, this is subject to change so might be a good idea to not specifiy.

Here's an example list.
This is a good place to define what your preferred name is if you have one.

* Jake Chen
* Nathaniel (Nate) Butterworth


## Course pre-requisites and setup requirements

No previous programming experience is required, will introduce you to fundamental Unix and HPC as required. Training will be delivered online, so you will need access to a modern computer with a stable internet connection. Participants will require the Sydney VPN and a terminal client (as per the [Setup Instructions](./setup.html) provided).


## Venue

TBD, online?
In almost all cases, our courses are delivered from Sydney and times are reported in AEST (GMT+10).

#### Zoom etiquette and how we interact

Sessions will be recorded and added to this page. Please interrupt whenever you want! Ideally, have your camera on and interact as much as possible. There will be someone monitoring the chat-window with any questions you would like to post there.  Three hours is a long Zoom session so we have plenty of scheduled breaks combined with a mix of hands-on content.


## Code of Conduct

As a University of Sydney course, we also want to make sure peopele are aware of our code of conduct.
Feel free to move this to an about page as needed. 

Example standard Code of Conduct statement: 

We expect all attendees of our training to follow our code of conduct, including bullying, harassment and discrimination prevention policies.

In order to foster a positive and professional learning environment we encourage the following kinds of behaviours at all our events and on our platforms:

* Use welcoming and inclusive language
* Be respectful of different viewpoints and experiences
* Gracefully accept constructive criticism
* Focus on what is best for the community
* Show courtesy and respect towards other community members

Our full CoC, with incident reporting guidelines, is available [here]https://sydney-informatics-hub.github.io/codeofconduct/).



## Schedule

If your training includes multiple components, it is always nice to have a table with the schedule.
With quarto we can make tables using markdown formating, like below.

|  |  |
| --- | :--- |
| **Intro** |
|   | [Intro to AlphaFold](notebooks/01_alphafold.qmd) |
|   | [Intro to HPC](notebooks/02_hpc.qmd) |
|   | [Artemis Example](notebooks/03_artemis.qmd) |
| **Advanced** |
|   | [Singularity Example](notebooks/04_singularity.qmd) |
|   | [NCI Example](notebooks/05_nci.qmd) |
|   | [Ronin Research Cloud (AWS) Example](notebooks/06_aws.qmd) |
|   | [ColabFold](notebooks/07_colabfold.qmd) |


## Setup Instructions

Please attempt to complete the [Setup Instructions](./setup.html) **before the course**. We will run through this in the course too.
