# Introduction to the High Performance Computing

## What is the Artemis HPC?

HPC stands for 'High Performance Computing', our local HPC is called "Artemis". You might colloquially refer to Artemis as a ‘supercomputer’. Technically, Artemis is a computing cluster, which is a whole lot of individual computers networked together. AS of 2023, Artemis consists of:

    * 7,636 cores (CPUs)
    * 45 TB of RAM
    * 108 NVIDIA V100 GPUs
    * 378 TB of storage
    * 56 Gbps FDR InfiniBand (networking)

Artemis computers (which we call `machines` or `nodes`) run a Linux operating system, ‘CentOS’ v6.10. Computing performed on Artemis nodes is managed by a `scheduler`, and ours is an instance of `PBS Pro`.

Artemis is ideal for calculations that require:

    * A long time to complete (long walltime)
    * High RAM usage
    * Big data input or outputs
    * Are able to use multiple cores or nodes to run in parallel, and hence much faster

If you do use Artemis for your research, please acknowledge us! This ensures that we continue to get the funding we need to provide you with what is really a first-grade computing resource. A suggested acknowledgment might say:

> The authors acknowledge the Sydney Informatics Hub and the University of Sydney’s high performance computing cluster, Artemis, for providing the computing resources that have contributed to the results reported herein.


## Getting an Artemis Account

Get an Artemis account by creating a project with Artemis HPC access in [Researcher Dashboard (DashR)](https://dashr.sydney.edu.au/).

Artemis is available free of charge to all University of Sydney researchers. You only need a unikey, and a valid Research Dashboard Research Data Management Plan with Artemis access enabled.

During the course you can be issued with an account belonging to the *Training* project.

## Connecting to Artemis

Connections to Artemis are remote connections – you’ll never sit at one of Artemis’ machines, which are stored in a secure data-centre in Western Sydney. Instead, you connect remotely into one of Artemis’ login nodes. Login nodes are Artemis machines that don’t perform any actual computing jobs, but simply provide users with an access gateway to Artemis’ filesystems and the PBS Pro job scheduler.

You can thus connect to Artemis from anywhere, requiring only a terminal emulator with an SSH client. (If you’re not on the USyd network (ie off-campus), you’ll also need to connect to the University’s VPN.

If you followed the [Setup instructions](https://sydney-informatics-hub.github.io/training.alphafold/setup.html), then you should already have the required software installed.

Once you are set up with an ssh client, connect with your unikey credentials with:

```bash
ssh -X <unikey>@hpc.sydney.edu.au
```
