# Running AlphaFold on the the Sydney Research Cloud (Ronin AWS)

## RONIN Research Cloud

If you find your workflows do not suit the queued environment of Gadi or Artemis, you may find creating your own computational stack to be most robust and adaptable.

Sydney offers researchers access to the AWS cloud via [Ronin](https://sydneyuni.atlassian.net/wiki/spaces/RC/pages/1108967637/RONIN+Research+Cloud). This interface allows creation and configuration of virtual machines on-demand with as many computational resources as you need for your current workload.

Generally, you will start with a bare-bones virtual machine. You may then install AlphaFold and the corresponding databases as per the installation instructions:

[https://github.com/google-deepmind/alphafold](https://github.com/google-deepmind/alphafold#installation-and-running-your-first-prediction)

## AWS and GCP public clouds

You may want to consult the native [AWS AlphaFold installation instructions](https://aws.amazon.com/blogs/machine-learning/run-alphafold-v2-0-on-amazon-ec2/) too, or the [Google Cloud Platform configuration steps](https://cloud.google.com/blog/products/ai-machine-learning/running-alphafold-on-vertexai) if you have ongoing AlphaFold requirements that can't be satisfied by a local installation.
