# Running AlphaFold with ColabFold on Google Colab

## What is ColabFold?

[ColabFold](https://github.com/sokrypton/ColabFold) is a fork of AlphaFold specifically designed for running on Google Colab resources. It is instantly accessible via Google Colab, or you can run the modified workflow on your own resources.


## What is Google Colab?

[Google Colab](https://colab.google/) is an online Python Notebook platform. Notebooks are powered by reasonable CPU, RAM, and GPU resources are available freely, only requiring a Google account. You can pay for a professional account for access to additional resources, but the free-tier is very useful!
You can run most Python packages and workflows within the Colab environment.


## How do I run AlphaFold with ColabFold?

There are few variations that use different tools in the pipeline all available [on the repo](https://github.com/sokrypton/ColabFold#making-protein-folding-accessible-to-all-via-google-colab).

This first notebook simply searches an amino acid sequence against the known databases. The actual prediction can take some time, from minutes to hours, depending on the length of the protein and what type of GPU google provides (as it can randomly vary). Follow the steps here:
[AlphaFold Colab](https://colab.research.google.com/github/deepmind/alphafold/blob/main/notebooks/AlphaFold.ipynb)


A more advanced version allows protein structure and complex prediction using AlphaFold2 and Alphafold2-multimer. Sequence alignments/templates are generated through MMseqs2 and HHsearch. 

Follow along: 
[AlphaFold2 using MMseqs2](https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/AlphaFold2.ipynb)


## What are the limitations of ColabFold?

You cannot automate searches as robustly as on command-line.
Google-Colab instances have time and computational resource limits on them.
